name: Go
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Test
        run: go test -v -cover ./...

      - name: Build
        run: go build -v .
